# This is a basic workflow to help you get started with Actions

name: Build and Test (iron)

# Controls when the action will run.
on:
  # Triggers the workflow on push
  push:
    branches: [ rolling ]

  # Triggers the workflow on pull requests
  pull_request:
    branches: [ rolling ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ros-tooling/setup-ros@v0.6
        with:
          use-ros2-testing: true
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: iron
